name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#deploy') }}
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch updates, rebuild and restart containers
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dev/InkGoose
            git reset --hard
            git pull
            echo ${{ secrets.PASSWORD }} | sudo docker-compose down
            echo ${{ secrets.PASSWORD }} | sudo docker compose build
            echo ${{ secrets.PASSWORD }} | sudo docker compose up -d
